// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_config_02.proto

#ifndef PROTOBUF_game_5fconfig_5f02_2eproto__INCLUDED
#define PROTOBUF_game_5fconfig_5f02_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "illusion.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_game_5fconfig_5f02_2eproto();
void protobuf_AssignDesc_game_5fconfig_5f02_2eproto();
void protobuf_ShutdownFile_game_5fconfig_5f02_2eproto();

class SUB_STRUCT_A;
class SUB_STRUCT_B;
class GAME_CFG_STRUCT_2;
class GAME_CFG_STRUCT_2_NESTED_STRUCT_C;
class GAME_CFG_STRUCT_2_NESTED_STRUCT_D;
class LIST_OF_GAME_CFG_STRUCT_2;

enum GAME_CFG_STRUCT_2_NESTED_ENUM {
  GAME_CFG_STRUCT_2_NESTED_ENUM_MON = 1,
  GAME_CFG_STRUCT_2_NESTED_ENUM_TUE = 2,
  GAME_CFG_STRUCT_2_NESTED_ENUM_WED = 3,
  GAME_CFG_STRUCT_2_NESTED_ENUM_THU = 4,
  GAME_CFG_STRUCT_2_NESTED_ENUM_FRI = 5,
  GAME_CFG_STRUCT_2_NESTED_ENUM_SAT = 6,
  GAME_CFG_STRUCT_2_NESTED_ENUM_SUN = 7
};
bool GAME_CFG_STRUCT_2_NESTED_ENUM_IsValid(int value);
const GAME_CFG_STRUCT_2_NESTED_ENUM GAME_CFG_STRUCT_2_NESTED_ENUM_NESTED_ENUM_MIN = GAME_CFG_STRUCT_2_NESTED_ENUM_MON;
const GAME_CFG_STRUCT_2_NESTED_ENUM GAME_CFG_STRUCT_2_NESTED_ENUM_NESTED_ENUM_MAX = GAME_CFG_STRUCT_2_NESTED_ENUM_SUN;
const int GAME_CFG_STRUCT_2_NESTED_ENUM_NESTED_ENUM_ARRAYSIZE = GAME_CFG_STRUCT_2_NESTED_ENUM_NESTED_ENUM_MAX + 1;

const ::google::protobuf::EnumDescriptor* GAME_CFG_STRUCT_2_NESTED_ENUM_descriptor();
inline const ::std::string& GAME_CFG_STRUCT_2_NESTED_ENUM_Name(GAME_CFG_STRUCT_2_NESTED_ENUM value) {
  return ::google::protobuf::internal::NameOfEnum(
    GAME_CFG_STRUCT_2_NESTED_ENUM_descriptor(), value);
}
inline bool GAME_CFG_STRUCT_2_NESTED_ENUM_Parse(
    const ::std::string& name, GAME_CFG_STRUCT_2_NESTED_ENUM* value) {
  return ::google::protobuf::internal::ParseNamedEnum<GAME_CFG_STRUCT_2_NESTED_ENUM>(
    GAME_CFG_STRUCT_2_NESTED_ENUM_descriptor(), name, value);
}
enum ENUM_COUNTRY {
  AUSTRALIA = 61,
  CHILE = 56,
  EGYPT = 20,
  FINLAND = 358,
  FRANCE = 33,
  GERMANY = 49,
  HONG_KONG = 852,
  ICELAND = 354,
  INDIA = 91,
  IRAN = 981,
  IRAQ = 964,
  IRELAND = 353,
  ITALY = 39,
  JAPAN = 81,
  MALAYSIA = 60,
  NORWAY = 47,
  PRCHINA = 86,
  POLAND = 48,
  RUSSIA = 7,
  SOUTH_KOREA = 82,
  SPAIN = 34,
  TAIWAN = 886,
  UNITED_STATES = 1
};
bool ENUM_COUNTRY_IsValid(int value);
const ENUM_COUNTRY ENUM_COUNTRY_MIN = UNITED_STATES;
const ENUM_COUNTRY ENUM_COUNTRY_MAX = IRAN;
const int ENUM_COUNTRY_ARRAYSIZE = ENUM_COUNTRY_MAX + 1;

const ::google::protobuf::EnumDescriptor* ENUM_COUNTRY_descriptor();
inline const ::std::string& ENUM_COUNTRY_Name(ENUM_COUNTRY value) {
  return ::google::protobuf::internal::NameOfEnum(
    ENUM_COUNTRY_descriptor(), value);
}
inline bool ENUM_COUNTRY_Parse(
    const ::std::string& name, ENUM_COUNTRY* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ENUM_COUNTRY>(
    ENUM_COUNTRY_descriptor(), name, value);
}
// ===================================================================

class SUB_STRUCT_A : public ::google::protobuf::Message {
 public:
  SUB_STRUCT_A();
  virtual ~SUB_STRUCT_A();

  SUB_STRUCT_A(const SUB_STRUCT_A& from);

  inline SUB_STRUCT_A& operator=(const SUB_STRUCT_A& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SUB_STRUCT_A& default_instance();

  void Swap(SUB_STRUCT_A* other);

  // implements Message ----------------------------------------------

  SUB_STRUCT_A* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SUB_STRUCT_A& from);
  void MergeFrom(const SUB_STRUCT_A& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double sub_a_1 = 1;
  inline bool has_sub_a_1() const;
  inline void clear_sub_a_1();
  static const int kSubA1FieldNumber = 1;
  inline double sub_a_1() const;
  inline void set_sub_a_1(double value);

  // optional double sub_a_2 = 2;
  inline bool has_sub_a_2() const;
  inline void clear_sub_a_2();
  static const int kSubA2FieldNumber = 2;
  inline double sub_a_2() const;
  inline void set_sub_a_2(double value);

  // optional string sub_a_3 = 3;
  inline bool has_sub_a_3() const;
  inline void clear_sub_a_3();
  static const int kSubA3FieldNumber = 3;
  inline const ::std::string& sub_a_3() const;
  inline void set_sub_a_3(const ::std::string& value);
  inline void set_sub_a_3(const char* value);
  inline void set_sub_a_3(const char* value, size_t size);
  inline ::std::string* mutable_sub_a_3();
  inline ::std::string* release_sub_a_3();
  inline void set_allocated_sub_a_3(::std::string* sub_a_3);

  // optional bytes sub_a_4 = 4;
  inline bool has_sub_a_4() const;
  inline void clear_sub_a_4();
  static const int kSubA4FieldNumber = 4;
  inline const ::std::string& sub_a_4() const;
  inline void set_sub_a_4(const ::std::string& value);
  inline void set_sub_a_4(const char* value);
  inline void set_sub_a_4(const void* value, size_t size);
  inline ::std::string* mutable_sub_a_4();
  inline ::std::string* release_sub_a_4();
  inline void set_allocated_sub_a_4(::std::string* sub_a_4);

  // @@protoc_insertion_point(class_scope:SUB_STRUCT_A)
 private:
  inline void set_has_sub_a_1();
  inline void clear_has_sub_a_1();
  inline void set_has_sub_a_2();
  inline void clear_has_sub_a_2();
  inline void set_has_sub_a_3();
  inline void clear_has_sub_a_3();
  inline void set_has_sub_a_4();
  inline void clear_has_sub_a_4();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double sub_a_1_;
  double sub_a_2_;
  ::std::string* sub_a_3_;
  ::std::string* sub_a_4_;
  friend void  protobuf_AddDesc_game_5fconfig_5f02_2eproto();
  friend void protobuf_AssignDesc_game_5fconfig_5f02_2eproto();
  friend void protobuf_ShutdownFile_game_5fconfig_5f02_2eproto();

  void InitAsDefaultInstance();
  static SUB_STRUCT_A* default_instance_;
};
// -------------------------------------------------------------------

class SUB_STRUCT_B : public ::google::protobuf::Message {
 public:
  SUB_STRUCT_B();
  virtual ~SUB_STRUCT_B();

  SUB_STRUCT_B(const SUB_STRUCT_B& from);

  inline SUB_STRUCT_B& operator=(const SUB_STRUCT_B& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SUB_STRUCT_B& default_instance();

  void Swap(SUB_STRUCT_B* other);

  // implements Message ----------------------------------------------

  SUB_STRUCT_B* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SUB_STRUCT_B& from);
  void MergeFrom(const SUB_STRUCT_B& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 sub_b_1 = 1;
  inline bool has_sub_b_1() const;
  inline void clear_sub_b_1();
  static const int kSubB1FieldNumber = 1;
  inline ::google::protobuf::int32 sub_b_1() const;
  inline void set_sub_b_1(::google::protobuf::int32 value);

  // optional int64 sub_b_2 = 2;
  inline bool has_sub_b_2() const;
  inline void clear_sub_b_2();
  static const int kSubB2FieldNumber = 2;
  inline ::google::protobuf::int64 sub_b_2() const;
  inline void set_sub_b_2(::google::protobuf::int64 value);

  // optional uint32 sub_b_3 = 3;
  inline bool has_sub_b_3() const;
  inline void clear_sub_b_3();
  static const int kSubB3FieldNumber = 3;
  inline ::google::protobuf::uint32 sub_b_3() const;
  inline void set_sub_b_3(::google::protobuf::uint32 value);

  // optional int64 sub_b_4 = 4;
  inline bool has_sub_b_4() const;
  inline void clear_sub_b_4();
  static const int kSubB4FieldNumber = 4;
  inline ::google::protobuf::int64 sub_b_4() const;
  inline void set_sub_b_4(::google::protobuf::int64 value);

  // optional int64 sub_b_5 = 5;
  inline bool has_sub_b_5() const;
  inline void clear_sub_b_5();
  static const int kSubB5FieldNumber = 5;
  inline ::google::protobuf::int64 sub_b_5() const;
  inline void set_sub_b_5(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:SUB_STRUCT_B)
 private:
  inline void set_has_sub_b_1();
  inline void clear_has_sub_b_1();
  inline void set_has_sub_b_2();
  inline void clear_has_sub_b_2();
  inline void set_has_sub_b_3();
  inline void clear_has_sub_b_3();
  inline void set_has_sub_b_4();
  inline void clear_has_sub_b_4();
  inline void set_has_sub_b_5();
  inline void clear_has_sub_b_5();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 sub_b_2_;
  ::google::protobuf::int32 sub_b_1_;
  ::google::protobuf::uint32 sub_b_3_;
  ::google::protobuf::int64 sub_b_4_;
  ::google::protobuf::int64 sub_b_5_;
  friend void  protobuf_AddDesc_game_5fconfig_5f02_2eproto();
  friend void protobuf_AssignDesc_game_5fconfig_5f02_2eproto();
  friend void protobuf_ShutdownFile_game_5fconfig_5f02_2eproto();

  void InitAsDefaultInstance();
  static SUB_STRUCT_B* default_instance_;
};
// -------------------------------------------------------------------

class GAME_CFG_STRUCT_2_NESTED_STRUCT_C : public ::google::protobuf::Message {
 public:
  GAME_CFG_STRUCT_2_NESTED_STRUCT_C();
  virtual ~GAME_CFG_STRUCT_2_NESTED_STRUCT_C();

  GAME_CFG_STRUCT_2_NESTED_STRUCT_C(const GAME_CFG_STRUCT_2_NESTED_STRUCT_C& from);

  inline GAME_CFG_STRUCT_2_NESTED_STRUCT_C& operator=(const GAME_CFG_STRUCT_2_NESTED_STRUCT_C& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GAME_CFG_STRUCT_2_NESTED_STRUCT_C& default_instance();

  void Swap(GAME_CFG_STRUCT_2_NESTED_STRUCT_C* other);

  // implements Message ----------------------------------------------

  GAME_CFG_STRUCT_2_NESTED_STRUCT_C* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GAME_CFG_STRUCT_2_NESTED_STRUCT_C& from);
  void MergeFrom(const GAME_CFG_STRUCT_2_NESTED_STRUCT_C& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional sint32 nested_c_1 = 1;
  inline bool has_nested_c_1() const;
  inline void clear_nested_c_1();
  static const int kNestedC1FieldNumber = 1;
  inline ::google::protobuf::int32 nested_c_1() const;
  inline void set_nested_c_1(::google::protobuf::int32 value);

  // optional sint64 nested_c_2 = 2;
  inline bool has_nested_c_2() const;
  inline void clear_nested_c_2();
  static const int kNestedC2FieldNumber = 2;
  inline ::google::protobuf::int64 nested_c_2() const;
  inline void set_nested_c_2(::google::protobuf::int64 value);

  // optional fixed32 nested_c_3 = 3;
  inline bool has_nested_c_3() const;
  inline void clear_nested_c_3();
  static const int kNestedC3FieldNumber = 3;
  inline ::google::protobuf::uint32 nested_c_3() const;
  inline void set_nested_c_3(::google::protobuf::uint32 value);

  // optional fixed64 nested_c_4 = 4;
  inline bool has_nested_c_4() const;
  inline void clear_nested_c_4();
  static const int kNestedC4FieldNumber = 4;
  inline ::google::protobuf::uint64 nested_c_4() const;
  inline void set_nested_c_4(::google::protobuf::uint64 value);

  // optional .GAME_CFG_STRUCT_2.NESTED_ENUM nested_c_5 = 5;
  inline bool has_nested_c_5() const;
  inline void clear_nested_c_5();
  static const int kNestedC5FieldNumber = 5;
  inline ::GAME_CFG_STRUCT_2_NESTED_ENUM nested_c_5() const;
  inline void set_nested_c_5(::GAME_CFG_STRUCT_2_NESTED_ENUM value);

  // @@protoc_insertion_point(class_scope:GAME_CFG_STRUCT_2.NESTED_STRUCT_C)
 private:
  inline void set_has_nested_c_1();
  inline void clear_has_nested_c_1();
  inline void set_has_nested_c_2();
  inline void clear_has_nested_c_2();
  inline void set_has_nested_c_3();
  inline void clear_has_nested_c_3();
  inline void set_has_nested_c_4();
  inline void clear_has_nested_c_4();
  inline void set_has_nested_c_5();
  inline void clear_has_nested_c_5();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 nested_c_2_;
  ::google::protobuf::int32 nested_c_1_;
  ::google::protobuf::uint32 nested_c_3_;
  ::google::protobuf::uint64 nested_c_4_;
  int nested_c_5_;
  friend void  protobuf_AddDesc_game_5fconfig_5f02_2eproto();
  friend void protobuf_AssignDesc_game_5fconfig_5f02_2eproto();
  friend void protobuf_ShutdownFile_game_5fconfig_5f02_2eproto();

  void InitAsDefaultInstance();
  static GAME_CFG_STRUCT_2_NESTED_STRUCT_C* default_instance_;
};
// -------------------------------------------------------------------

class GAME_CFG_STRUCT_2_NESTED_STRUCT_D : public ::google::protobuf::Message {
 public:
  GAME_CFG_STRUCT_2_NESTED_STRUCT_D();
  virtual ~GAME_CFG_STRUCT_2_NESTED_STRUCT_D();

  GAME_CFG_STRUCT_2_NESTED_STRUCT_D(const GAME_CFG_STRUCT_2_NESTED_STRUCT_D& from);

  inline GAME_CFG_STRUCT_2_NESTED_STRUCT_D& operator=(const GAME_CFG_STRUCT_2_NESTED_STRUCT_D& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GAME_CFG_STRUCT_2_NESTED_STRUCT_D& default_instance();

  void Swap(GAME_CFG_STRUCT_2_NESTED_STRUCT_D* other);

  // implements Message ----------------------------------------------

  GAME_CFG_STRUCT_2_NESTED_STRUCT_D* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GAME_CFG_STRUCT_2_NESTED_STRUCT_D& from);
  void MergeFrom(const GAME_CFG_STRUCT_2_NESTED_STRUCT_D& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional sfixed32 nested_d_1 = 1;
  inline bool has_nested_d_1() const;
  inline void clear_nested_d_1();
  static const int kNestedD1FieldNumber = 1;
  inline ::google::protobuf::int32 nested_d_1() const;
  inline void set_nested_d_1(::google::protobuf::int32 value);

  // optional sfixed64 nested_d_2 = 2;
  inline bool has_nested_d_2() const;
  inline void clear_nested_d_2();
  static const int kNestedD2FieldNumber = 2;
  inline ::google::protobuf::int64 nested_d_2() const;
  inline void set_nested_d_2(::google::protobuf::int64 value);

  // optional string nested_d_3 = 3;
  inline bool has_nested_d_3() const;
  inline void clear_nested_d_3();
  static const int kNestedD3FieldNumber = 3;
  inline const ::std::string& nested_d_3() const;
  inline void set_nested_d_3(const ::std::string& value);
  inline void set_nested_d_3(const char* value);
  inline void set_nested_d_3(const char* value, size_t size);
  inline ::std::string* mutable_nested_d_3();
  inline ::std::string* release_nested_d_3();
  inline void set_allocated_nested_d_3(::std::string* nested_d_3);

  // optional bytes nested_d_4 = 4;
  inline bool has_nested_d_4() const;
  inline void clear_nested_d_4();
  static const int kNestedD4FieldNumber = 4;
  inline const ::std::string& nested_d_4() const;
  inline void set_nested_d_4(const ::std::string& value);
  inline void set_nested_d_4(const char* value);
  inline void set_nested_d_4(const void* value, size_t size);
  inline ::std::string* mutable_nested_d_4();
  inline ::std::string* release_nested_d_4();
  inline void set_allocated_nested_d_4(::std::string* nested_d_4);

  // @@protoc_insertion_point(class_scope:GAME_CFG_STRUCT_2.NESTED_STRUCT_D)
 private:
  inline void set_has_nested_d_1();
  inline void clear_has_nested_d_1();
  inline void set_has_nested_d_2();
  inline void clear_has_nested_d_2();
  inline void set_has_nested_d_3();
  inline void clear_has_nested_d_3();
  inline void set_has_nested_d_4();
  inline void clear_has_nested_d_4();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 nested_d_2_;
  ::std::string* nested_d_3_;
  ::std::string* nested_d_4_;
  ::google::protobuf::int32 nested_d_1_;
  friend void  protobuf_AddDesc_game_5fconfig_5f02_2eproto();
  friend void protobuf_AssignDesc_game_5fconfig_5f02_2eproto();
  friend void protobuf_ShutdownFile_game_5fconfig_5f02_2eproto();

  void InitAsDefaultInstance();
  static GAME_CFG_STRUCT_2_NESTED_STRUCT_D* default_instance_;
};
// -------------------------------------------------------------------

class GAME_CFG_STRUCT_2 : public ::google::protobuf::Message {
 public:
  GAME_CFG_STRUCT_2();
  virtual ~GAME_CFG_STRUCT_2();

  GAME_CFG_STRUCT_2(const GAME_CFG_STRUCT_2& from);

  inline GAME_CFG_STRUCT_2& operator=(const GAME_CFG_STRUCT_2& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GAME_CFG_STRUCT_2& default_instance();

  void Swap(GAME_CFG_STRUCT_2* other);

  // implements Message ----------------------------------------------

  GAME_CFG_STRUCT_2* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GAME_CFG_STRUCT_2& from);
  void MergeFrom(const GAME_CFG_STRUCT_2& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef GAME_CFG_STRUCT_2_NESTED_STRUCT_C NESTED_STRUCT_C;
  typedef GAME_CFG_STRUCT_2_NESTED_STRUCT_D NESTED_STRUCT_D;

  typedef GAME_CFG_STRUCT_2_NESTED_ENUM NESTED_ENUM;
  static const NESTED_ENUM MON = GAME_CFG_STRUCT_2_NESTED_ENUM_MON;
  static const NESTED_ENUM TUE = GAME_CFG_STRUCT_2_NESTED_ENUM_TUE;
  static const NESTED_ENUM WED = GAME_CFG_STRUCT_2_NESTED_ENUM_WED;
  static const NESTED_ENUM THU = GAME_CFG_STRUCT_2_NESTED_ENUM_THU;
  static const NESTED_ENUM FRI = GAME_CFG_STRUCT_2_NESTED_ENUM_FRI;
  static const NESTED_ENUM SAT = GAME_CFG_STRUCT_2_NESTED_ENUM_SAT;
  static const NESTED_ENUM SUN = GAME_CFG_STRUCT_2_NESTED_ENUM_SUN;
  static inline bool NESTED_ENUM_IsValid(int value) {
    return GAME_CFG_STRUCT_2_NESTED_ENUM_IsValid(value);
  }
  static const NESTED_ENUM NESTED_ENUM_MIN =
    GAME_CFG_STRUCT_2_NESTED_ENUM_NESTED_ENUM_MIN;
  static const NESTED_ENUM NESTED_ENUM_MAX =
    GAME_CFG_STRUCT_2_NESTED_ENUM_NESTED_ENUM_MAX;
  static const int NESTED_ENUM_ARRAYSIZE =
    GAME_CFG_STRUCT_2_NESTED_ENUM_NESTED_ENUM_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  NESTED_ENUM_descriptor() {
    return GAME_CFG_STRUCT_2_NESTED_ENUM_descriptor();
  }
  static inline const ::std::string& NESTED_ENUM_Name(NESTED_ENUM value) {
    return GAME_CFG_STRUCT_2_NESTED_ENUM_Name(value);
  }
  static inline bool NESTED_ENUM_Parse(const ::std::string& name,
      NESTED_ENUM* value) {
    return GAME_CFG_STRUCT_2_NESTED_ENUM_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional int32 s2_a = 1;
  inline bool has_s2_a() const;
  inline void clear_s2_a();
  static const int kS2AFieldNumber = 1;
  inline ::google::protobuf::int32 s2_a() const;
  inline void set_s2_a(::google::protobuf::int32 value);

  // optional int32 s2_b = 2;
  inline bool has_s2_b() const;
  inline void clear_s2_b();
  static const int kS2BFieldNumber = 2;
  inline ::google::protobuf::int32 s2_b() const;
  inline void set_s2_b(::google::protobuf::int32 value);

  // optional uint32 s2_c = 3;
  inline bool has_s2_c() const;
  inline void clear_s2_c();
  static const int kS2CFieldNumber = 3;
  inline ::google::protobuf::uint32 s2_c() const;
  inline void set_s2_c(::google::protobuf::uint32 value);

  // repeated uint64 s2_d = 4;
  inline int s2_d_size() const;
  inline void clear_s2_d();
  static const int kS2DFieldNumber = 4;
  inline ::google::protobuf::uint64 s2_d(int index) const;
  inline void set_s2_d(int index, ::google::protobuf::uint64 value);
  inline void add_s2_d(::google::protobuf::uint64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      s2_d() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_s2_d();

  // optional .SUB_STRUCT_A s2_e = 5;
  inline bool has_s2_e() const;
  inline void clear_s2_e();
  static const int kS2EFieldNumber = 5;
  inline const ::SUB_STRUCT_A& s2_e() const;
  inline ::SUB_STRUCT_A* mutable_s2_e();
  inline ::SUB_STRUCT_A* release_s2_e();
  inline void set_allocated_s2_e(::SUB_STRUCT_A* s2_e);

  // repeated .SUB_STRUCT_B s2_f = 6;
  inline int s2_f_size() const;
  inline void clear_s2_f();
  static const int kS2FFieldNumber = 6;
  inline const ::SUB_STRUCT_B& s2_f(int index) const;
  inline ::SUB_STRUCT_B* mutable_s2_f(int index);
  inline ::SUB_STRUCT_B* add_s2_f();
  inline const ::google::protobuf::RepeatedPtrField< ::SUB_STRUCT_B >&
      s2_f() const;
  inline ::google::protobuf::RepeatedPtrField< ::SUB_STRUCT_B >*
      mutable_s2_f();

  // optional .GAME_CFG_STRUCT_2.NESTED_STRUCT_C s2_g = 7;
  inline bool has_s2_g() const;
  inline void clear_s2_g();
  static const int kS2GFieldNumber = 7;
  inline const ::GAME_CFG_STRUCT_2_NESTED_STRUCT_C& s2_g() const;
  inline ::GAME_CFG_STRUCT_2_NESTED_STRUCT_C* mutable_s2_g();
  inline ::GAME_CFG_STRUCT_2_NESTED_STRUCT_C* release_s2_g();
  inline void set_allocated_s2_g(::GAME_CFG_STRUCT_2_NESTED_STRUCT_C* s2_g);

  // repeated .GAME_CFG_STRUCT_2.NESTED_STRUCT_D s2_h = 8;
  inline int s2_h_size() const;
  inline void clear_s2_h();
  static const int kS2HFieldNumber = 8;
  inline const ::GAME_CFG_STRUCT_2_NESTED_STRUCT_D& s2_h(int index) const;
  inline ::GAME_CFG_STRUCT_2_NESTED_STRUCT_D* mutable_s2_h(int index);
  inline ::GAME_CFG_STRUCT_2_NESTED_STRUCT_D* add_s2_h();
  inline const ::google::protobuf::RepeatedPtrField< ::GAME_CFG_STRUCT_2_NESTED_STRUCT_D >&
      s2_h() const;
  inline ::google::protobuf::RepeatedPtrField< ::GAME_CFG_STRUCT_2_NESTED_STRUCT_D >*
      mutable_s2_h();

  // optional .GAME_CFG_STRUCT_2.NESTED_ENUM s2_i = 9;
  inline bool has_s2_i() const;
  inline void clear_s2_i();
  static const int kS2IFieldNumber = 9;
  inline ::GAME_CFG_STRUCT_2_NESTED_ENUM s2_i() const;
  inline void set_s2_i(::GAME_CFG_STRUCT_2_NESTED_ENUM value);

  // required .ENUM_COUNTRY s2_j = 10;
  inline bool has_s2_j() const;
  inline void clear_s2_j();
  static const int kS2JFieldNumber = 10;
  inline ::ENUM_COUNTRY s2_j() const;
  inline void set_s2_j(::ENUM_COUNTRY value);

  // @@protoc_insertion_point(class_scope:GAME_CFG_STRUCT_2)
 private:
  inline void set_has_s2_a();
  inline void clear_has_s2_a();
  inline void set_has_s2_b();
  inline void clear_has_s2_b();
  inline void set_has_s2_c();
  inline void clear_has_s2_c();
  inline void set_has_s2_e();
  inline void clear_has_s2_e();
  inline void set_has_s2_g();
  inline void clear_has_s2_g();
  inline void set_has_s2_i();
  inline void clear_has_s2_i();
  inline void set_has_s2_j();
  inline void clear_has_s2_j();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 s2_a_;
  ::google::protobuf::int32 s2_b_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > s2_d_;
  ::SUB_STRUCT_A* s2_e_;
  ::google::protobuf::RepeatedPtrField< ::SUB_STRUCT_B > s2_f_;
  ::google::protobuf::uint32 s2_c_;
  int s2_i_;
  ::GAME_CFG_STRUCT_2_NESTED_STRUCT_C* s2_g_;
  ::google::protobuf::RepeatedPtrField< ::GAME_CFG_STRUCT_2_NESTED_STRUCT_D > s2_h_;
  int s2_j_;
  friend void  protobuf_AddDesc_game_5fconfig_5f02_2eproto();
  friend void protobuf_AssignDesc_game_5fconfig_5f02_2eproto();
  friend void protobuf_ShutdownFile_game_5fconfig_5f02_2eproto();

  void InitAsDefaultInstance();
  static GAME_CFG_STRUCT_2* default_instance_;
};
// -------------------------------------------------------------------

class LIST_OF_GAME_CFG_STRUCT_2 : public ::google::protobuf::Message {
 public:
  LIST_OF_GAME_CFG_STRUCT_2();
  virtual ~LIST_OF_GAME_CFG_STRUCT_2();

  LIST_OF_GAME_CFG_STRUCT_2(const LIST_OF_GAME_CFG_STRUCT_2& from);

  inline LIST_OF_GAME_CFG_STRUCT_2& operator=(const LIST_OF_GAME_CFG_STRUCT_2& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LIST_OF_GAME_CFG_STRUCT_2& default_instance();

  void Swap(LIST_OF_GAME_CFG_STRUCT_2* other);

  // implements Message ----------------------------------------------

  LIST_OF_GAME_CFG_STRUCT_2* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LIST_OF_GAME_CFG_STRUCT_2& from);
  void MergeFrom(const LIST_OF_GAME_CFG_STRUCT_2& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .GAME_CFG_STRUCT_2 list_data = 1;
  inline int list_data_size() const;
  inline void clear_list_data();
  static const int kListDataFieldNumber = 1;
  inline const ::GAME_CFG_STRUCT_2& list_data(int index) const;
  inline ::GAME_CFG_STRUCT_2* mutable_list_data(int index);
  inline ::GAME_CFG_STRUCT_2* add_list_data();
  inline const ::google::protobuf::RepeatedPtrField< ::GAME_CFG_STRUCT_2 >&
      list_data() const;
  inline ::google::protobuf::RepeatedPtrField< ::GAME_CFG_STRUCT_2 >*
      mutable_list_data();

  // @@protoc_insertion_point(class_scope:LIST_OF_GAME_CFG_STRUCT_2)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::GAME_CFG_STRUCT_2 > list_data_;
  friend void  protobuf_AddDesc_game_5fconfig_5f02_2eproto();
  friend void protobuf_AssignDesc_game_5fconfig_5f02_2eproto();
  friend void protobuf_ShutdownFile_game_5fconfig_5f02_2eproto();

  void InitAsDefaultInstance();
  static LIST_OF_GAME_CFG_STRUCT_2* default_instance_;
};
// ===================================================================


// ===================================================================

// SUB_STRUCT_A

// optional double sub_a_1 = 1;
inline bool SUB_STRUCT_A::has_sub_a_1() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SUB_STRUCT_A::set_has_sub_a_1() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SUB_STRUCT_A::clear_has_sub_a_1() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SUB_STRUCT_A::clear_sub_a_1() {
  sub_a_1_ = 0;
  clear_has_sub_a_1();
}
inline double SUB_STRUCT_A::sub_a_1() const {
  // @@protoc_insertion_point(field_get:SUB_STRUCT_A.sub_a_1)
  return sub_a_1_;
}
inline void SUB_STRUCT_A::set_sub_a_1(double value) {
  set_has_sub_a_1();
  sub_a_1_ = value;
  // @@protoc_insertion_point(field_set:SUB_STRUCT_A.sub_a_1)
}

// optional double sub_a_2 = 2;
inline bool SUB_STRUCT_A::has_sub_a_2() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SUB_STRUCT_A::set_has_sub_a_2() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SUB_STRUCT_A::clear_has_sub_a_2() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SUB_STRUCT_A::clear_sub_a_2() {
  sub_a_2_ = 0;
  clear_has_sub_a_2();
}
inline double SUB_STRUCT_A::sub_a_2() const {
  // @@protoc_insertion_point(field_get:SUB_STRUCT_A.sub_a_2)
  return sub_a_2_;
}
inline void SUB_STRUCT_A::set_sub_a_2(double value) {
  set_has_sub_a_2();
  sub_a_2_ = value;
  // @@protoc_insertion_point(field_set:SUB_STRUCT_A.sub_a_2)
}

// optional string sub_a_3 = 3;
inline bool SUB_STRUCT_A::has_sub_a_3() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SUB_STRUCT_A::set_has_sub_a_3() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SUB_STRUCT_A::clear_has_sub_a_3() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SUB_STRUCT_A::clear_sub_a_3() {
  if (sub_a_3_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sub_a_3_->clear();
  }
  clear_has_sub_a_3();
}
inline const ::std::string& SUB_STRUCT_A::sub_a_3() const {
  // @@protoc_insertion_point(field_get:SUB_STRUCT_A.sub_a_3)
  return *sub_a_3_;
}
inline void SUB_STRUCT_A::set_sub_a_3(const ::std::string& value) {
  set_has_sub_a_3();
  if (sub_a_3_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sub_a_3_ = new ::std::string;
  }
  sub_a_3_->assign(value);
  // @@protoc_insertion_point(field_set:SUB_STRUCT_A.sub_a_3)
}
inline void SUB_STRUCT_A::set_sub_a_3(const char* value) {
  set_has_sub_a_3();
  if (sub_a_3_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sub_a_3_ = new ::std::string;
  }
  sub_a_3_->assign(value);
  // @@protoc_insertion_point(field_set_char:SUB_STRUCT_A.sub_a_3)
}
inline void SUB_STRUCT_A::set_sub_a_3(const char* value, size_t size) {
  set_has_sub_a_3();
  if (sub_a_3_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sub_a_3_ = new ::std::string;
  }
  sub_a_3_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:SUB_STRUCT_A.sub_a_3)
}
inline ::std::string* SUB_STRUCT_A::mutable_sub_a_3() {
  set_has_sub_a_3();
  if (sub_a_3_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sub_a_3_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:SUB_STRUCT_A.sub_a_3)
  return sub_a_3_;
}
inline ::std::string* SUB_STRUCT_A::release_sub_a_3() {
  clear_has_sub_a_3();
  if (sub_a_3_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = sub_a_3_;
    sub_a_3_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void SUB_STRUCT_A::set_allocated_sub_a_3(::std::string* sub_a_3) {
  if (sub_a_3_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete sub_a_3_;
  }
  if (sub_a_3) {
    set_has_sub_a_3();
    sub_a_3_ = sub_a_3;
  } else {
    clear_has_sub_a_3();
    sub_a_3_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:SUB_STRUCT_A.sub_a_3)
}

// optional bytes sub_a_4 = 4;
inline bool SUB_STRUCT_A::has_sub_a_4() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void SUB_STRUCT_A::set_has_sub_a_4() {
  _has_bits_[0] |= 0x00000008u;
}
inline void SUB_STRUCT_A::clear_has_sub_a_4() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void SUB_STRUCT_A::clear_sub_a_4() {
  if (sub_a_4_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sub_a_4_->clear();
  }
  clear_has_sub_a_4();
}
inline const ::std::string& SUB_STRUCT_A::sub_a_4() const {
  // @@protoc_insertion_point(field_get:SUB_STRUCT_A.sub_a_4)
  return *sub_a_4_;
}
inline void SUB_STRUCT_A::set_sub_a_4(const ::std::string& value) {
  set_has_sub_a_4();
  if (sub_a_4_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sub_a_4_ = new ::std::string;
  }
  sub_a_4_->assign(value);
  // @@protoc_insertion_point(field_set:SUB_STRUCT_A.sub_a_4)
}
inline void SUB_STRUCT_A::set_sub_a_4(const char* value) {
  set_has_sub_a_4();
  if (sub_a_4_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sub_a_4_ = new ::std::string;
  }
  sub_a_4_->assign(value);
  // @@protoc_insertion_point(field_set_char:SUB_STRUCT_A.sub_a_4)
}
inline void SUB_STRUCT_A::set_sub_a_4(const void* value, size_t size) {
  set_has_sub_a_4();
  if (sub_a_4_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sub_a_4_ = new ::std::string;
  }
  sub_a_4_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:SUB_STRUCT_A.sub_a_4)
}
inline ::std::string* SUB_STRUCT_A::mutable_sub_a_4() {
  set_has_sub_a_4();
  if (sub_a_4_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sub_a_4_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:SUB_STRUCT_A.sub_a_4)
  return sub_a_4_;
}
inline ::std::string* SUB_STRUCT_A::release_sub_a_4() {
  clear_has_sub_a_4();
  if (sub_a_4_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = sub_a_4_;
    sub_a_4_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void SUB_STRUCT_A::set_allocated_sub_a_4(::std::string* sub_a_4) {
  if (sub_a_4_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete sub_a_4_;
  }
  if (sub_a_4) {
    set_has_sub_a_4();
    sub_a_4_ = sub_a_4;
  } else {
    clear_has_sub_a_4();
    sub_a_4_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:SUB_STRUCT_A.sub_a_4)
}

// -------------------------------------------------------------------

// SUB_STRUCT_B

// optional int32 sub_b_1 = 1;
inline bool SUB_STRUCT_B::has_sub_b_1() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SUB_STRUCT_B::set_has_sub_b_1() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SUB_STRUCT_B::clear_has_sub_b_1() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SUB_STRUCT_B::clear_sub_b_1() {
  sub_b_1_ = 0;
  clear_has_sub_b_1();
}
inline ::google::protobuf::int32 SUB_STRUCT_B::sub_b_1() const {
  // @@protoc_insertion_point(field_get:SUB_STRUCT_B.sub_b_1)
  return sub_b_1_;
}
inline void SUB_STRUCT_B::set_sub_b_1(::google::protobuf::int32 value) {
  set_has_sub_b_1();
  sub_b_1_ = value;
  // @@protoc_insertion_point(field_set:SUB_STRUCT_B.sub_b_1)
}

// optional int64 sub_b_2 = 2;
inline bool SUB_STRUCT_B::has_sub_b_2() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SUB_STRUCT_B::set_has_sub_b_2() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SUB_STRUCT_B::clear_has_sub_b_2() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SUB_STRUCT_B::clear_sub_b_2() {
  sub_b_2_ = GOOGLE_LONGLONG(0);
  clear_has_sub_b_2();
}
inline ::google::protobuf::int64 SUB_STRUCT_B::sub_b_2() const {
  // @@protoc_insertion_point(field_get:SUB_STRUCT_B.sub_b_2)
  return sub_b_2_;
}
inline void SUB_STRUCT_B::set_sub_b_2(::google::protobuf::int64 value) {
  set_has_sub_b_2();
  sub_b_2_ = value;
  // @@protoc_insertion_point(field_set:SUB_STRUCT_B.sub_b_2)
}

// optional uint32 sub_b_3 = 3;
inline bool SUB_STRUCT_B::has_sub_b_3() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SUB_STRUCT_B::set_has_sub_b_3() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SUB_STRUCT_B::clear_has_sub_b_3() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SUB_STRUCT_B::clear_sub_b_3() {
  sub_b_3_ = 0u;
  clear_has_sub_b_3();
}
inline ::google::protobuf::uint32 SUB_STRUCT_B::sub_b_3() const {
  // @@protoc_insertion_point(field_get:SUB_STRUCT_B.sub_b_3)
  return sub_b_3_;
}
inline void SUB_STRUCT_B::set_sub_b_3(::google::protobuf::uint32 value) {
  set_has_sub_b_3();
  sub_b_3_ = value;
  // @@protoc_insertion_point(field_set:SUB_STRUCT_B.sub_b_3)
}

// optional int64 sub_b_4 = 4;
inline bool SUB_STRUCT_B::has_sub_b_4() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void SUB_STRUCT_B::set_has_sub_b_4() {
  _has_bits_[0] |= 0x00000008u;
}
inline void SUB_STRUCT_B::clear_has_sub_b_4() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void SUB_STRUCT_B::clear_sub_b_4() {
  sub_b_4_ = GOOGLE_LONGLONG(0);
  clear_has_sub_b_4();
}
inline ::google::protobuf::int64 SUB_STRUCT_B::sub_b_4() const {
  // @@protoc_insertion_point(field_get:SUB_STRUCT_B.sub_b_4)
  return sub_b_4_;
}
inline void SUB_STRUCT_B::set_sub_b_4(::google::protobuf::int64 value) {
  set_has_sub_b_4();
  sub_b_4_ = value;
  // @@protoc_insertion_point(field_set:SUB_STRUCT_B.sub_b_4)
}

// optional int64 sub_b_5 = 5;
inline bool SUB_STRUCT_B::has_sub_b_5() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void SUB_STRUCT_B::set_has_sub_b_5() {
  _has_bits_[0] |= 0x00000010u;
}
inline void SUB_STRUCT_B::clear_has_sub_b_5() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void SUB_STRUCT_B::clear_sub_b_5() {
  sub_b_5_ = GOOGLE_LONGLONG(0);
  clear_has_sub_b_5();
}
inline ::google::protobuf::int64 SUB_STRUCT_B::sub_b_5() const {
  // @@protoc_insertion_point(field_get:SUB_STRUCT_B.sub_b_5)
  return sub_b_5_;
}
inline void SUB_STRUCT_B::set_sub_b_5(::google::protobuf::int64 value) {
  set_has_sub_b_5();
  sub_b_5_ = value;
  // @@protoc_insertion_point(field_set:SUB_STRUCT_B.sub_b_5)
}

// -------------------------------------------------------------------

// GAME_CFG_STRUCT_2_NESTED_STRUCT_C

// optional sint32 nested_c_1 = 1;
inline bool GAME_CFG_STRUCT_2_NESTED_STRUCT_C::has_nested_c_1() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_C::set_has_nested_c_1() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_C::clear_has_nested_c_1() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_C::clear_nested_c_1() {
  nested_c_1_ = 0;
  clear_has_nested_c_1();
}
inline ::google::protobuf::int32 GAME_CFG_STRUCT_2_NESTED_STRUCT_C::nested_c_1() const {
  // @@protoc_insertion_point(field_get:GAME_CFG_STRUCT_2.NESTED_STRUCT_C.nested_c_1)
  return nested_c_1_;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_C::set_nested_c_1(::google::protobuf::int32 value) {
  set_has_nested_c_1();
  nested_c_1_ = value;
  // @@protoc_insertion_point(field_set:GAME_CFG_STRUCT_2.NESTED_STRUCT_C.nested_c_1)
}

// optional sint64 nested_c_2 = 2;
inline bool GAME_CFG_STRUCT_2_NESTED_STRUCT_C::has_nested_c_2() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_C::set_has_nested_c_2() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_C::clear_has_nested_c_2() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_C::clear_nested_c_2() {
  nested_c_2_ = GOOGLE_LONGLONG(0);
  clear_has_nested_c_2();
}
inline ::google::protobuf::int64 GAME_CFG_STRUCT_2_NESTED_STRUCT_C::nested_c_2() const {
  // @@protoc_insertion_point(field_get:GAME_CFG_STRUCT_2.NESTED_STRUCT_C.nested_c_2)
  return nested_c_2_;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_C::set_nested_c_2(::google::protobuf::int64 value) {
  set_has_nested_c_2();
  nested_c_2_ = value;
  // @@protoc_insertion_point(field_set:GAME_CFG_STRUCT_2.NESTED_STRUCT_C.nested_c_2)
}

// optional fixed32 nested_c_3 = 3;
inline bool GAME_CFG_STRUCT_2_NESTED_STRUCT_C::has_nested_c_3() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_C::set_has_nested_c_3() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_C::clear_has_nested_c_3() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_C::clear_nested_c_3() {
  nested_c_3_ = 0u;
  clear_has_nested_c_3();
}
inline ::google::protobuf::uint32 GAME_CFG_STRUCT_2_NESTED_STRUCT_C::nested_c_3() const {
  // @@protoc_insertion_point(field_get:GAME_CFG_STRUCT_2.NESTED_STRUCT_C.nested_c_3)
  return nested_c_3_;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_C::set_nested_c_3(::google::protobuf::uint32 value) {
  set_has_nested_c_3();
  nested_c_3_ = value;
  // @@protoc_insertion_point(field_set:GAME_CFG_STRUCT_2.NESTED_STRUCT_C.nested_c_3)
}

// optional fixed64 nested_c_4 = 4;
inline bool GAME_CFG_STRUCT_2_NESTED_STRUCT_C::has_nested_c_4() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_C::set_has_nested_c_4() {
  _has_bits_[0] |= 0x00000008u;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_C::clear_has_nested_c_4() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_C::clear_nested_c_4() {
  nested_c_4_ = GOOGLE_ULONGLONG(0);
  clear_has_nested_c_4();
}
inline ::google::protobuf::uint64 GAME_CFG_STRUCT_2_NESTED_STRUCT_C::nested_c_4() const {
  // @@protoc_insertion_point(field_get:GAME_CFG_STRUCT_2.NESTED_STRUCT_C.nested_c_4)
  return nested_c_4_;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_C::set_nested_c_4(::google::protobuf::uint64 value) {
  set_has_nested_c_4();
  nested_c_4_ = value;
  // @@protoc_insertion_point(field_set:GAME_CFG_STRUCT_2.NESTED_STRUCT_C.nested_c_4)
}

// optional .GAME_CFG_STRUCT_2.NESTED_ENUM nested_c_5 = 5;
inline bool GAME_CFG_STRUCT_2_NESTED_STRUCT_C::has_nested_c_5() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_C::set_has_nested_c_5() {
  _has_bits_[0] |= 0x00000010u;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_C::clear_has_nested_c_5() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_C::clear_nested_c_5() {
  nested_c_5_ = 1;
  clear_has_nested_c_5();
}
inline ::GAME_CFG_STRUCT_2_NESTED_ENUM GAME_CFG_STRUCT_2_NESTED_STRUCT_C::nested_c_5() const {
  // @@protoc_insertion_point(field_get:GAME_CFG_STRUCT_2.NESTED_STRUCT_C.nested_c_5)
  return static_cast< ::GAME_CFG_STRUCT_2_NESTED_ENUM >(nested_c_5_);
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_C::set_nested_c_5(::GAME_CFG_STRUCT_2_NESTED_ENUM value) {
  assert(::GAME_CFG_STRUCT_2_NESTED_ENUM_IsValid(value));
  set_has_nested_c_5();
  nested_c_5_ = value;
  // @@protoc_insertion_point(field_set:GAME_CFG_STRUCT_2.NESTED_STRUCT_C.nested_c_5)
}

// -------------------------------------------------------------------

// GAME_CFG_STRUCT_2_NESTED_STRUCT_D

// optional sfixed32 nested_d_1 = 1;
inline bool GAME_CFG_STRUCT_2_NESTED_STRUCT_D::has_nested_d_1() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_D::set_has_nested_d_1() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_D::clear_has_nested_d_1() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_D::clear_nested_d_1() {
  nested_d_1_ = 0;
  clear_has_nested_d_1();
}
inline ::google::protobuf::int32 GAME_CFG_STRUCT_2_NESTED_STRUCT_D::nested_d_1() const {
  // @@protoc_insertion_point(field_get:GAME_CFG_STRUCT_2.NESTED_STRUCT_D.nested_d_1)
  return nested_d_1_;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_D::set_nested_d_1(::google::protobuf::int32 value) {
  set_has_nested_d_1();
  nested_d_1_ = value;
  // @@protoc_insertion_point(field_set:GAME_CFG_STRUCT_2.NESTED_STRUCT_D.nested_d_1)
}

// optional sfixed64 nested_d_2 = 2;
inline bool GAME_CFG_STRUCT_2_NESTED_STRUCT_D::has_nested_d_2() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_D::set_has_nested_d_2() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_D::clear_has_nested_d_2() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_D::clear_nested_d_2() {
  nested_d_2_ = GOOGLE_LONGLONG(0);
  clear_has_nested_d_2();
}
inline ::google::protobuf::int64 GAME_CFG_STRUCT_2_NESTED_STRUCT_D::nested_d_2() const {
  // @@protoc_insertion_point(field_get:GAME_CFG_STRUCT_2.NESTED_STRUCT_D.nested_d_2)
  return nested_d_2_;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_D::set_nested_d_2(::google::protobuf::int64 value) {
  set_has_nested_d_2();
  nested_d_2_ = value;
  // @@protoc_insertion_point(field_set:GAME_CFG_STRUCT_2.NESTED_STRUCT_D.nested_d_2)
}

// optional string nested_d_3 = 3;
inline bool GAME_CFG_STRUCT_2_NESTED_STRUCT_D::has_nested_d_3() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_D::set_has_nested_d_3() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_D::clear_has_nested_d_3() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_D::clear_nested_d_3() {
  if (nested_d_3_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    nested_d_3_->clear();
  }
  clear_has_nested_d_3();
}
inline const ::std::string& GAME_CFG_STRUCT_2_NESTED_STRUCT_D::nested_d_3() const {
  // @@protoc_insertion_point(field_get:GAME_CFG_STRUCT_2.NESTED_STRUCT_D.nested_d_3)
  return *nested_d_3_;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_D::set_nested_d_3(const ::std::string& value) {
  set_has_nested_d_3();
  if (nested_d_3_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    nested_d_3_ = new ::std::string;
  }
  nested_d_3_->assign(value);
  // @@protoc_insertion_point(field_set:GAME_CFG_STRUCT_2.NESTED_STRUCT_D.nested_d_3)
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_D::set_nested_d_3(const char* value) {
  set_has_nested_d_3();
  if (nested_d_3_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    nested_d_3_ = new ::std::string;
  }
  nested_d_3_->assign(value);
  // @@protoc_insertion_point(field_set_char:GAME_CFG_STRUCT_2.NESTED_STRUCT_D.nested_d_3)
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_D::set_nested_d_3(const char* value, size_t size) {
  set_has_nested_d_3();
  if (nested_d_3_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    nested_d_3_ = new ::std::string;
  }
  nested_d_3_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:GAME_CFG_STRUCT_2.NESTED_STRUCT_D.nested_d_3)
}
inline ::std::string* GAME_CFG_STRUCT_2_NESTED_STRUCT_D::mutable_nested_d_3() {
  set_has_nested_d_3();
  if (nested_d_3_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    nested_d_3_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:GAME_CFG_STRUCT_2.NESTED_STRUCT_D.nested_d_3)
  return nested_d_3_;
}
inline ::std::string* GAME_CFG_STRUCT_2_NESTED_STRUCT_D::release_nested_d_3() {
  clear_has_nested_d_3();
  if (nested_d_3_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = nested_d_3_;
    nested_d_3_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_D::set_allocated_nested_d_3(::std::string* nested_d_3) {
  if (nested_d_3_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete nested_d_3_;
  }
  if (nested_d_3) {
    set_has_nested_d_3();
    nested_d_3_ = nested_d_3;
  } else {
    clear_has_nested_d_3();
    nested_d_3_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:GAME_CFG_STRUCT_2.NESTED_STRUCT_D.nested_d_3)
}

// optional bytes nested_d_4 = 4;
inline bool GAME_CFG_STRUCT_2_NESTED_STRUCT_D::has_nested_d_4() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_D::set_has_nested_d_4() {
  _has_bits_[0] |= 0x00000008u;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_D::clear_has_nested_d_4() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_D::clear_nested_d_4() {
  if (nested_d_4_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    nested_d_4_->clear();
  }
  clear_has_nested_d_4();
}
inline const ::std::string& GAME_CFG_STRUCT_2_NESTED_STRUCT_D::nested_d_4() const {
  // @@protoc_insertion_point(field_get:GAME_CFG_STRUCT_2.NESTED_STRUCT_D.nested_d_4)
  return *nested_d_4_;
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_D::set_nested_d_4(const ::std::string& value) {
  set_has_nested_d_4();
  if (nested_d_4_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    nested_d_4_ = new ::std::string;
  }
  nested_d_4_->assign(value);
  // @@protoc_insertion_point(field_set:GAME_CFG_STRUCT_2.NESTED_STRUCT_D.nested_d_4)
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_D::set_nested_d_4(const char* value) {
  set_has_nested_d_4();
  if (nested_d_4_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    nested_d_4_ = new ::std::string;
  }
  nested_d_4_->assign(value);
  // @@protoc_insertion_point(field_set_char:GAME_CFG_STRUCT_2.NESTED_STRUCT_D.nested_d_4)
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_D::set_nested_d_4(const void* value, size_t size) {
  set_has_nested_d_4();
  if (nested_d_4_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    nested_d_4_ = new ::std::string;
  }
  nested_d_4_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:GAME_CFG_STRUCT_2.NESTED_STRUCT_D.nested_d_4)
}
inline ::std::string* GAME_CFG_STRUCT_2_NESTED_STRUCT_D::mutable_nested_d_4() {
  set_has_nested_d_4();
  if (nested_d_4_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    nested_d_4_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:GAME_CFG_STRUCT_2.NESTED_STRUCT_D.nested_d_4)
  return nested_d_4_;
}
inline ::std::string* GAME_CFG_STRUCT_2_NESTED_STRUCT_D::release_nested_d_4() {
  clear_has_nested_d_4();
  if (nested_d_4_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = nested_d_4_;
    nested_d_4_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void GAME_CFG_STRUCT_2_NESTED_STRUCT_D::set_allocated_nested_d_4(::std::string* nested_d_4) {
  if (nested_d_4_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete nested_d_4_;
  }
  if (nested_d_4) {
    set_has_nested_d_4();
    nested_d_4_ = nested_d_4;
  } else {
    clear_has_nested_d_4();
    nested_d_4_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:GAME_CFG_STRUCT_2.NESTED_STRUCT_D.nested_d_4)
}

// -------------------------------------------------------------------

// GAME_CFG_STRUCT_2

// optional int32 s2_a = 1;
inline bool GAME_CFG_STRUCT_2::has_s2_a() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GAME_CFG_STRUCT_2::set_has_s2_a() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GAME_CFG_STRUCT_2::clear_has_s2_a() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GAME_CFG_STRUCT_2::clear_s2_a() {
  s2_a_ = 0;
  clear_has_s2_a();
}
inline ::google::protobuf::int32 GAME_CFG_STRUCT_2::s2_a() const {
  // @@protoc_insertion_point(field_get:GAME_CFG_STRUCT_2.s2_a)
  return s2_a_;
}
inline void GAME_CFG_STRUCT_2::set_s2_a(::google::protobuf::int32 value) {
  set_has_s2_a();
  s2_a_ = value;
  // @@protoc_insertion_point(field_set:GAME_CFG_STRUCT_2.s2_a)
}

// optional int32 s2_b = 2;
inline bool GAME_CFG_STRUCT_2::has_s2_b() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GAME_CFG_STRUCT_2::set_has_s2_b() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GAME_CFG_STRUCT_2::clear_has_s2_b() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GAME_CFG_STRUCT_2::clear_s2_b() {
  s2_b_ = 0;
  clear_has_s2_b();
}
inline ::google::protobuf::int32 GAME_CFG_STRUCT_2::s2_b() const {
  // @@protoc_insertion_point(field_get:GAME_CFG_STRUCT_2.s2_b)
  return s2_b_;
}
inline void GAME_CFG_STRUCT_2::set_s2_b(::google::protobuf::int32 value) {
  set_has_s2_b();
  s2_b_ = value;
  // @@protoc_insertion_point(field_set:GAME_CFG_STRUCT_2.s2_b)
}

// optional uint32 s2_c = 3;
inline bool GAME_CFG_STRUCT_2::has_s2_c() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GAME_CFG_STRUCT_2::set_has_s2_c() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GAME_CFG_STRUCT_2::clear_has_s2_c() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GAME_CFG_STRUCT_2::clear_s2_c() {
  s2_c_ = 0u;
  clear_has_s2_c();
}
inline ::google::protobuf::uint32 GAME_CFG_STRUCT_2::s2_c() const {
  // @@protoc_insertion_point(field_get:GAME_CFG_STRUCT_2.s2_c)
  return s2_c_;
}
inline void GAME_CFG_STRUCT_2::set_s2_c(::google::protobuf::uint32 value) {
  set_has_s2_c();
  s2_c_ = value;
  // @@protoc_insertion_point(field_set:GAME_CFG_STRUCT_2.s2_c)
}

// repeated uint64 s2_d = 4;
inline int GAME_CFG_STRUCT_2::s2_d_size() const {
  return s2_d_.size();
}
inline void GAME_CFG_STRUCT_2::clear_s2_d() {
  s2_d_.Clear();
}
inline ::google::protobuf::uint64 GAME_CFG_STRUCT_2::s2_d(int index) const {
  // @@protoc_insertion_point(field_get:GAME_CFG_STRUCT_2.s2_d)
  return s2_d_.Get(index);
}
inline void GAME_CFG_STRUCT_2::set_s2_d(int index, ::google::protobuf::uint64 value) {
  s2_d_.Set(index, value);
  // @@protoc_insertion_point(field_set:GAME_CFG_STRUCT_2.s2_d)
}
inline void GAME_CFG_STRUCT_2::add_s2_d(::google::protobuf::uint64 value) {
  s2_d_.Add(value);
  // @@protoc_insertion_point(field_add:GAME_CFG_STRUCT_2.s2_d)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
GAME_CFG_STRUCT_2::s2_d() const {
  // @@protoc_insertion_point(field_list:GAME_CFG_STRUCT_2.s2_d)
  return s2_d_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
GAME_CFG_STRUCT_2::mutable_s2_d() {
  // @@protoc_insertion_point(field_mutable_list:GAME_CFG_STRUCT_2.s2_d)
  return &s2_d_;
}

// optional .SUB_STRUCT_A s2_e = 5;
inline bool GAME_CFG_STRUCT_2::has_s2_e() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void GAME_CFG_STRUCT_2::set_has_s2_e() {
  _has_bits_[0] |= 0x00000010u;
}
inline void GAME_CFG_STRUCT_2::clear_has_s2_e() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void GAME_CFG_STRUCT_2::clear_s2_e() {
  if (s2_e_ != NULL) s2_e_->::SUB_STRUCT_A::Clear();
  clear_has_s2_e();
}
inline const ::SUB_STRUCT_A& GAME_CFG_STRUCT_2::s2_e() const {
  // @@protoc_insertion_point(field_get:GAME_CFG_STRUCT_2.s2_e)
  return s2_e_ != NULL ? *s2_e_ : *default_instance_->s2_e_;
}
inline ::SUB_STRUCT_A* GAME_CFG_STRUCT_2::mutable_s2_e() {
  set_has_s2_e();
  if (s2_e_ == NULL) s2_e_ = new ::SUB_STRUCT_A;
  // @@protoc_insertion_point(field_mutable:GAME_CFG_STRUCT_2.s2_e)
  return s2_e_;
}
inline ::SUB_STRUCT_A* GAME_CFG_STRUCT_2::release_s2_e() {
  clear_has_s2_e();
  ::SUB_STRUCT_A* temp = s2_e_;
  s2_e_ = NULL;
  return temp;
}
inline void GAME_CFG_STRUCT_2::set_allocated_s2_e(::SUB_STRUCT_A* s2_e) {
  delete s2_e_;
  s2_e_ = s2_e;
  if (s2_e) {
    set_has_s2_e();
  } else {
    clear_has_s2_e();
  }
  // @@protoc_insertion_point(field_set_allocated:GAME_CFG_STRUCT_2.s2_e)
}

// repeated .SUB_STRUCT_B s2_f = 6;
inline int GAME_CFG_STRUCT_2::s2_f_size() const {
  return s2_f_.size();
}
inline void GAME_CFG_STRUCT_2::clear_s2_f() {
  s2_f_.Clear();
}
inline const ::SUB_STRUCT_B& GAME_CFG_STRUCT_2::s2_f(int index) const {
  // @@protoc_insertion_point(field_get:GAME_CFG_STRUCT_2.s2_f)
  return s2_f_.Get(index);
}
inline ::SUB_STRUCT_B* GAME_CFG_STRUCT_2::mutable_s2_f(int index) {
  // @@protoc_insertion_point(field_mutable:GAME_CFG_STRUCT_2.s2_f)
  return s2_f_.Mutable(index);
}
inline ::SUB_STRUCT_B* GAME_CFG_STRUCT_2::add_s2_f() {
  // @@protoc_insertion_point(field_add:GAME_CFG_STRUCT_2.s2_f)
  return s2_f_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::SUB_STRUCT_B >&
GAME_CFG_STRUCT_2::s2_f() const {
  // @@protoc_insertion_point(field_list:GAME_CFG_STRUCT_2.s2_f)
  return s2_f_;
}
inline ::google::protobuf::RepeatedPtrField< ::SUB_STRUCT_B >*
GAME_CFG_STRUCT_2::mutable_s2_f() {
  // @@protoc_insertion_point(field_mutable_list:GAME_CFG_STRUCT_2.s2_f)
  return &s2_f_;
}

// optional .GAME_CFG_STRUCT_2.NESTED_STRUCT_C s2_g = 7;
inline bool GAME_CFG_STRUCT_2::has_s2_g() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void GAME_CFG_STRUCT_2::set_has_s2_g() {
  _has_bits_[0] |= 0x00000040u;
}
inline void GAME_CFG_STRUCT_2::clear_has_s2_g() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void GAME_CFG_STRUCT_2::clear_s2_g() {
  if (s2_g_ != NULL) s2_g_->::GAME_CFG_STRUCT_2_NESTED_STRUCT_C::Clear();
  clear_has_s2_g();
}
inline const ::GAME_CFG_STRUCT_2_NESTED_STRUCT_C& GAME_CFG_STRUCT_2::s2_g() const {
  // @@protoc_insertion_point(field_get:GAME_CFG_STRUCT_2.s2_g)
  return s2_g_ != NULL ? *s2_g_ : *default_instance_->s2_g_;
}
inline ::GAME_CFG_STRUCT_2_NESTED_STRUCT_C* GAME_CFG_STRUCT_2::mutable_s2_g() {
  set_has_s2_g();
  if (s2_g_ == NULL) s2_g_ = new ::GAME_CFG_STRUCT_2_NESTED_STRUCT_C;
  // @@protoc_insertion_point(field_mutable:GAME_CFG_STRUCT_2.s2_g)
  return s2_g_;
}
inline ::GAME_CFG_STRUCT_2_NESTED_STRUCT_C* GAME_CFG_STRUCT_2::release_s2_g() {
  clear_has_s2_g();
  ::GAME_CFG_STRUCT_2_NESTED_STRUCT_C* temp = s2_g_;
  s2_g_ = NULL;
  return temp;
}
inline void GAME_CFG_STRUCT_2::set_allocated_s2_g(::GAME_CFG_STRUCT_2_NESTED_STRUCT_C* s2_g) {
  delete s2_g_;
  s2_g_ = s2_g;
  if (s2_g) {
    set_has_s2_g();
  } else {
    clear_has_s2_g();
  }
  // @@protoc_insertion_point(field_set_allocated:GAME_CFG_STRUCT_2.s2_g)
}

// repeated .GAME_CFG_STRUCT_2.NESTED_STRUCT_D s2_h = 8;
inline int GAME_CFG_STRUCT_2::s2_h_size() const {
  return s2_h_.size();
}
inline void GAME_CFG_STRUCT_2::clear_s2_h() {
  s2_h_.Clear();
}
inline const ::GAME_CFG_STRUCT_2_NESTED_STRUCT_D& GAME_CFG_STRUCT_2::s2_h(int index) const {
  // @@protoc_insertion_point(field_get:GAME_CFG_STRUCT_2.s2_h)
  return s2_h_.Get(index);
}
inline ::GAME_CFG_STRUCT_2_NESTED_STRUCT_D* GAME_CFG_STRUCT_2::mutable_s2_h(int index) {
  // @@protoc_insertion_point(field_mutable:GAME_CFG_STRUCT_2.s2_h)
  return s2_h_.Mutable(index);
}
inline ::GAME_CFG_STRUCT_2_NESTED_STRUCT_D* GAME_CFG_STRUCT_2::add_s2_h() {
  // @@protoc_insertion_point(field_add:GAME_CFG_STRUCT_2.s2_h)
  return s2_h_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::GAME_CFG_STRUCT_2_NESTED_STRUCT_D >&
GAME_CFG_STRUCT_2::s2_h() const {
  // @@protoc_insertion_point(field_list:GAME_CFG_STRUCT_2.s2_h)
  return s2_h_;
}
inline ::google::protobuf::RepeatedPtrField< ::GAME_CFG_STRUCT_2_NESTED_STRUCT_D >*
GAME_CFG_STRUCT_2::mutable_s2_h() {
  // @@protoc_insertion_point(field_mutable_list:GAME_CFG_STRUCT_2.s2_h)
  return &s2_h_;
}

// optional .GAME_CFG_STRUCT_2.NESTED_ENUM s2_i = 9;
inline bool GAME_CFG_STRUCT_2::has_s2_i() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void GAME_CFG_STRUCT_2::set_has_s2_i() {
  _has_bits_[0] |= 0x00000100u;
}
inline void GAME_CFG_STRUCT_2::clear_has_s2_i() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void GAME_CFG_STRUCT_2::clear_s2_i() {
  s2_i_ = 1;
  clear_has_s2_i();
}
inline ::GAME_CFG_STRUCT_2_NESTED_ENUM GAME_CFG_STRUCT_2::s2_i() const {
  // @@protoc_insertion_point(field_get:GAME_CFG_STRUCT_2.s2_i)
  return static_cast< ::GAME_CFG_STRUCT_2_NESTED_ENUM >(s2_i_);
}
inline void GAME_CFG_STRUCT_2::set_s2_i(::GAME_CFG_STRUCT_2_NESTED_ENUM value) {
  assert(::GAME_CFG_STRUCT_2_NESTED_ENUM_IsValid(value));
  set_has_s2_i();
  s2_i_ = value;
  // @@protoc_insertion_point(field_set:GAME_CFG_STRUCT_2.s2_i)
}

// required .ENUM_COUNTRY s2_j = 10;
inline bool GAME_CFG_STRUCT_2::has_s2_j() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void GAME_CFG_STRUCT_2::set_has_s2_j() {
  _has_bits_[0] |= 0x00000200u;
}
inline void GAME_CFG_STRUCT_2::clear_has_s2_j() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void GAME_CFG_STRUCT_2::clear_s2_j() {
  s2_j_ = 61;
  clear_has_s2_j();
}
inline ::ENUM_COUNTRY GAME_CFG_STRUCT_2::s2_j() const {
  // @@protoc_insertion_point(field_get:GAME_CFG_STRUCT_2.s2_j)
  return static_cast< ::ENUM_COUNTRY >(s2_j_);
}
inline void GAME_CFG_STRUCT_2::set_s2_j(::ENUM_COUNTRY value) {
  assert(::ENUM_COUNTRY_IsValid(value));
  set_has_s2_j();
  s2_j_ = value;
  // @@protoc_insertion_point(field_set:GAME_CFG_STRUCT_2.s2_j)
}

// -------------------------------------------------------------------

// LIST_OF_GAME_CFG_STRUCT_2

// repeated .GAME_CFG_STRUCT_2 list_data = 1;
inline int LIST_OF_GAME_CFG_STRUCT_2::list_data_size() const {
  return list_data_.size();
}
inline void LIST_OF_GAME_CFG_STRUCT_2::clear_list_data() {
  list_data_.Clear();
}
inline const ::GAME_CFG_STRUCT_2& LIST_OF_GAME_CFG_STRUCT_2::list_data(int index) const {
  // @@protoc_insertion_point(field_get:LIST_OF_GAME_CFG_STRUCT_2.list_data)
  return list_data_.Get(index);
}
inline ::GAME_CFG_STRUCT_2* LIST_OF_GAME_CFG_STRUCT_2::mutable_list_data(int index) {
  // @@protoc_insertion_point(field_mutable:LIST_OF_GAME_CFG_STRUCT_2.list_data)
  return list_data_.Mutable(index);
}
inline ::GAME_CFG_STRUCT_2* LIST_OF_GAME_CFG_STRUCT_2::add_list_data() {
  // @@protoc_insertion_point(field_add:LIST_OF_GAME_CFG_STRUCT_2.list_data)
  return list_data_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::GAME_CFG_STRUCT_2 >&
LIST_OF_GAME_CFG_STRUCT_2::list_data() const {
  // @@protoc_insertion_point(field_list:LIST_OF_GAME_CFG_STRUCT_2.list_data)
  return list_data_;
}
inline ::google::protobuf::RepeatedPtrField< ::GAME_CFG_STRUCT_2 >*
LIST_OF_GAME_CFG_STRUCT_2::mutable_list_data() {
  // @@protoc_insertion_point(field_mutable_list:LIST_OF_GAME_CFG_STRUCT_2.list_data)
  return &list_data_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::GAME_CFG_STRUCT_2_NESTED_ENUM> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::GAME_CFG_STRUCT_2_NESTED_ENUM>() {
  return ::GAME_CFG_STRUCT_2_NESTED_ENUM_descriptor();
}
template <> struct is_proto_enum< ::ENUM_COUNTRY> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ENUM_COUNTRY>() {
  return ::ENUM_COUNTRY_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_game_5fconfig_5f02_2eproto__INCLUDED
