// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: illusion.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "illusion.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace illusion {

namespace {


}  // namespace


void protobuf_AssignDesc_illusion_2eproto() {
  protobuf_AddDesc_illusion_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "illusion.proto");
  GOOGLE_CHECK(file != NULL);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_illusion_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_illusion_2eproto() {
}

void protobuf_AddDesc_illusion_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::protobuf_AddDesc_google_2fprotobuf_2fdescriptor_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\016illusion.proto\022\010illusion\032 google/proto"
    "buf/descriptor.proto:B\n\020illusion_message"
    "\022\037.google.protobuf.MessageOptions\030\321\206\003 \001("
    "\010:\005false:5\n\nexcel_file\022\037.google.protobuf"
    ".MessageOptions\030\322\206\003 \001(\t:6\n\013excel_sheet\022\037"
    ".google.protobuf.MessageOptions\030\323\206\003 \001(\t:"
    "=\n\017fieldsname_line\022\037.google.protobuf.Mes"
    "sageOptions\030\324\206\003 \001(\005:\0011:;\n\rfullname_line\022"
    "\037.google.protobuf.MessageOptions\030\325\206\003 \001(\005"
    ":\0012:7\n\tread_line\022\037.google.protobuf.Messa"
    "geOptions\030\326\206\003 \001(\005:\0013:5\n\nouter_file\022\037.goo"
    "gle.protobuf.MessageOptions\030\327\206\003 \001(\t:=\n\016i"
    "llusion_field\022\035.google.protobuf.FieldOpt"
    "ions\030\271\216\003 \001(\010:\004true:4\n\013fields_name\022\035.goog"
    "le.protobuf.FieldOptions\030\272\216\003 \001(\t:4\n\013repe"
    "at_size\022\035.google.protobuf.FieldOptions\030\273"
    "\216\003 \001(\005", 646);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "illusion.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::MessageOptions::default_instance(),
    50001, 8, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::MessageOptions::default_instance(),
    50002, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::MessageOptions::default_instance(),
    50003, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::MessageOptions::default_instance(),
    50004, 5, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::MessageOptions::default_instance(),
    50005, 5, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::MessageOptions::default_instance(),
    50006, 5, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::MessageOptions::default_instance(),
    50007, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    51001, 8, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    51002, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    51003, 5, false, false);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_illusion_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_illusion_2eproto {
  StaticDescriptorInitializer_illusion_2eproto() {
    protobuf_AddDesc_illusion_2eproto();
  }
} static_descriptor_initializer_illusion_2eproto_;
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  illusion_message(kIllusionMessageFieldNumber, false);
const ::std::string excel_file_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  excel_file(kExcelFileFieldNumber, excel_file_default);
const ::std::string excel_sheet_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  excel_sheet(kExcelSheetFieldNumber, excel_sheet_default);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  fieldsname_line(kFieldsnameLineFieldNumber, 1);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  fullname_line(kFullnameLineFieldNumber, 2);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  read_line(kReadLineFieldNumber, 3);
const ::std::string outer_file_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  outer_file(kOuterFileFieldNumber, outer_file_default);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  illusion_field(kIllusionFieldFieldNumber, true);
const ::std::string fields_name_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  fields_name(kFieldsNameFieldNumber, fields_name_default);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  repeat_size(kRepeatSizeFieldNumber, 0);

// @@protoc_insertion_point(namespace_scope)

}  // namespace illusion

// @@protoc_insertion_point(global_scope)
